### ISSUE TITLE
[NEW ACCOUNT] apsychogirl

### ISSUE THREAD

**Issue by bijjybox** [dgplug/blogs#6]
## Your IRC nickname
apsychogirl
## New accountname

- apsychogirl

**Comment by kushaldas** [comment]
Hi, we don't see you participating in dgplug. Can you please explain why do you need an account in blogs.dgplug.org?

**Comment by bijjybox** [comment]
Hi Kushal, I've joined dgplug a few weeks ago. I liked the virtual class that's being going on in the channel. So, I thought to contribute as well.

**Comment by kushaldas** [comment]
> Hi Kushal, I've joined dgplug a few weeks ago. I liked the virtual class that's being going on in the channel. So, I thought to contribute as well.

Please participate in the sessions, and also talk to other members in the group. We will recheck next week and decide on the account. There is no way to verify for us right now that you are willing to spend time there and help/learn from each other.
